//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFolderBrowser.Properties
{
	using System;


	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfFolderBrowser.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to AddToMruList cannot be changed while dialog is showing.
		/// </summary>
		internal static string AddToMruList {
			get {
				return ResourceManager.GetString("AddToMruList", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CheckFileExists cannot be changed while dialog is showing.
		/// </summary>
		internal static string CheckFileExists {
			get {
				return ResourceManager.GetString("CheckFileExists", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CheckPathExists cannot be changed while dialog is showing.
		/// </summary>
		internal static string CheckPathExists {
			get {
				return ResourceManager.GetString("CheckPathExists", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CheckReadOnly cannot be changed while dialog is showing.
		/// </summary>
		internal static string CheckReadOnly {
			get {
				return ResourceManager.GetString("CheckReadOnly", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to CheckValidNames cannot be changed while dialog is showing.
		/// </summary>
		internal static string CheckValidNames {
			get {
				return ResourceManager.GetString("CheckValidNames", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to DereferenceLinks cannot be changed while dialog is showing.
		/// </summary>
		internal static string DereferenceLinks {
			get {
				return ResourceManager.GetString("DereferenceLinks", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to cannot be changed while dialog is showing.
		/// </summary>
		internal static string IllegalPropertyChangeString {
			get {
				return ResourceManager.GetString("IllegalPropertyChangeString", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to RestoreDirectory cannot be changed while dialog is showing.
		/// </summary>
		internal static string RestoreDirectory {
			get {
				return ResourceManager.GetString("RestoreDirectory", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ShowHiddenItems cannot be changed while dialog is showing.
		/// </summary>
		internal static string ShowHiddenItems {
			get {
				return ResourceManager.GetString("ShowHiddenItems", resourceCulture);
			}
		}

		/// <summary>
		///   Looks up a localized string similar to ShowPlacesList cannot be changed while dialog is showing.
		/// </summary>
		internal static string ShowPlacesList {
			get {
				return ResourceManager.GetString("ShowPlacesList", resourceCulture);
			}
		}
	}
}
